---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-charts
  namespace: default
spec:
  interval: 10m0s
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
